### PR TITLE
POST method support

### PR DESCRIPTION
**Pull request by Pmmlabs**
I know that you will not merge this request, but I want to help someone who are searching for CORS-proxy with POST support. It was needed for me, therefore I implemented this and now I can share.
Just don't close this PR.

### CODE REVIEW

**Comment by liam4** [comment]
(It's worth mentioning #6 here, for anybody reading that issue.)

**Comment by JogoShugh** [comment]
@Pmmlabs thanks for doing this, we have used it successfully! As for merging this, it seems like it could be done if there's a way for it to be turned off by a setting so that @technoboy10 doesn't need to enable it for the production crossorigin.me web site. (Maybe that setting already exists?)

**Comment by Pmmlabs** [comment]
@JogoShugh do you mean some constant variable at the source beginning? because  there is no other settings engine. 
If so, it will be necessary to write in readme about this, because it not obvious.

**Comment by technoboy10** [comment]
Thanks for the PR! I'm not planning on implementing POST in the current version of crossorigin.me, but it's potentially in the works for version 2.0.

**Pull request closed without merging**
